//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.17379.
// 
#pragma warning disable 1591

namespace TravelAgency.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FlightServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelatedEnd))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StructuralObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(vuelo[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityKeyMember[]))]
    public partial class FlightService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback buscarVuelosOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarVuelos2OperationCompleted;
        
        private System.Threading.SendOrPostCallback listaAeropuertosOperationCompleted;
        
        private System.Threading.SendOrPostCallback capacidadVueloOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FlightService() {
            this.Url = global::TravelAgency.Properties.Settings.Default.TravelAgency_localhost_FlightService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event buscarVuelosCompletedEventHandler buscarVuelosCompleted;
        
        /// <remarks/>
        public event buscarVuelos2CompletedEventHandler buscarVuelos2Completed;
        
        /// <remarks/>
        public event listaAeropuertosCompletedEventHandler listaAeropuertosCompleted;
        
        /// <remarks/>
        public event capacidadVueloCompletedEventHandler capacidadVueloCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarVuelos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public vuelo[] buscarVuelos(string partida, string destino, string fecha) {
            object[] results = this.Invoke("buscarVuelos", new object[] {
                        partida,
                        destino,
                        fecha});
            return ((vuelo[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarVuelosAsync(string partida, string destino, string fecha) {
            this.buscarVuelosAsync(partida, destino, fecha, null);
        }
        
        /// <remarks/>
        public void buscarVuelosAsync(string partida, string destino, string fecha, object userState) {
            if ((this.buscarVuelosOperationCompleted == null)) {
                this.buscarVuelosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarVuelosOperationCompleted);
            }
            this.InvokeAsync("buscarVuelos", new object[] {
                        partida,
                        destino,
                        fecha}, this.buscarVuelosOperationCompleted, userState);
        }
        
        private void OnbuscarVuelosOperationCompleted(object arg) {
            if ((this.buscarVuelosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarVuelosCompleted(this, new buscarVuelosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarVuelos2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public vuelo[] buscarVuelos2() {
            object[] results = this.Invoke("buscarVuelos2", new object[0]);
            return ((vuelo[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarVuelos2Async() {
            this.buscarVuelos2Async(null);
        }
        
        /// <remarks/>
        public void buscarVuelos2Async(object userState) {
            if ((this.buscarVuelos2OperationCompleted == null)) {
                this.buscarVuelos2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarVuelos2OperationCompleted);
            }
            this.InvokeAsync("buscarVuelos2", new object[0], this.buscarVuelos2OperationCompleted, userState);
        }
        
        private void OnbuscarVuelos2OperationCompleted(object arg) {
            if ((this.buscarVuelos2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarVuelos2Completed(this, new buscarVuelos2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listaAeropuertos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public aeropuerto[] listaAeropuertos() {
            object[] results = this.Invoke("listaAeropuertos", new object[0]);
            return ((aeropuerto[])(results[0]));
        }
        
        /// <remarks/>
        public void listaAeropuertosAsync() {
            this.listaAeropuertosAsync(null);
        }
        
        /// <remarks/>
        public void listaAeropuertosAsync(object userState) {
            if ((this.listaAeropuertosOperationCompleted == null)) {
                this.listaAeropuertosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaAeropuertosOperationCompleted);
            }
            this.InvokeAsync("listaAeropuertos", new object[0], this.listaAeropuertosOperationCompleted, userState);
        }
        
        private void OnlistaAeropuertosOperationCompleted(object arg) {
            if ((this.listaAeropuertosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listaAeropuertosCompleted(this, new listaAeropuertosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/capacidadVuelo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public avion[] capacidadVuelo(int vuelo) {
            object[] results = this.Invoke("capacidadVuelo", new object[] {
                        vuelo});
            return ((avion[])(results[0]));
        }
        
        /// <remarks/>
        public void capacidadVueloAsync(int vuelo) {
            this.capacidadVueloAsync(vuelo, null);
        }
        
        /// <remarks/>
        public void capacidadVueloAsync(int vuelo, object userState) {
            if ((this.capacidadVueloOperationCompleted == null)) {
                this.capacidadVueloOperationCompleted = new System.Threading.SendOrPostCallback(this.OncapacidadVueloOperationCompleted);
            }
            this.InvokeAsync("capacidadVuelo", new object[] {
                        vuelo}, this.capacidadVueloOperationCompleted, userState);
        }
        
        private void OncapacidadVueloOperationCompleted(object arg) {
            if ((this.capacidadVueloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.capacidadVueloCompleted(this, new capacidadVueloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class vuelo : EntityObject {
        
        private int codigoField;
        
        private string aerolineaField;
        
        private string origenField;
        
        private string destinoField;
        
        private int avionField;
        
        private System.DateTime salidaField;
        
        private System.DateTime llegadaField;
        
        private System.Nullable<sbyte> estadoField;
        
        private EntityReferenceOfaerolinea aerolinea1ReferenceField;
        
        private EntityReferenceOfaeropuerto aeropuertoReferenceField;
        
        private EntityReferenceOfaeropuerto aeropuerto1ReferenceField;
        
        private EntityReferenceOfavion avion1ReferenceField;
        
        /// <remarks/>
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string aerolinea {
            get {
                return this.aerolineaField;
            }
            set {
                this.aerolineaField = value;
            }
        }
        
        /// <remarks/>
        public string origen {
            get {
                return this.origenField;
            }
            set {
                this.origenField = value;
            }
        }
        
        /// <remarks/>
        public string destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
            }
        }
        
        /// <remarks/>
        public int avion {
            get {
                return this.avionField;
            }
            set {
                this.avionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime salida {
            get {
                return this.salidaField;
            }
            set {
                this.salidaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime llegada {
            get {
                return this.llegadaField;
            }
            set {
                this.llegadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<sbyte> estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfaerolinea aerolinea1Reference {
            get {
                return this.aerolinea1ReferenceField;
            }
            set {
                this.aerolinea1ReferenceField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfaeropuerto aeropuertoReference {
            get {
                return this.aeropuertoReferenceField;
            }
            set {
                this.aeropuertoReferenceField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfaeropuerto aeropuerto1Reference {
            get {
                return this.aeropuerto1ReferenceField;
            }
            set {
                this.aeropuerto1ReferenceField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfavion avion1Reference {
            get {
                return this.avion1ReferenceField;
            }
            set {
                this.avion1ReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityReferenceOfaerolinea : EntityReference {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfaeropuerto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfavion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfaerolinea))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityReference : RelatedEnd {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKey {
        
        private string entitySetNameField;
        
        private string entityContainerNameField;
        
        private EntityKeyMember[] entityKeyValuesField;
        
        /// <remarks/>
        public string EntitySetName {
            get {
                return this.entitySetNameField;
            }
            set {
                this.entitySetNameField = value;
            }
        }
        
        /// <remarks/>
        public string EntityContainerName {
            get {
                return this.entityContainerNameField;
            }
            set {
                this.entityContainerNameField = value;
            }
        }
        
        /// <remarks/>
        public EntityKeyMember[] EntityKeyValues {
            get {
                return this.entityKeyValuesField;
            }
            set {
                this.entityKeyValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKeyMember {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfaeropuerto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfavion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfaerolinea))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class RelatedEnd {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(avion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(aeropuerto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(vuelo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class StructuralObject {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(avion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(aeropuerto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(vuelo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityObject : StructuralObject {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class avion : EntityObject {
        
        private int codigoField;
        
        private string descripcionField;
        
        private int capacidadField;
        
        /// <remarks/>
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public int capacidad {
            get {
                return this.capacidadField;
            }
            set {
                this.capacidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class aeropuerto : EntityObject {
        
        private string codigoField;
        
        private string descripcionField;
        
        private string ciudadField;
        
        private string paisField;
        
        private string direccionField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
            }
        }
        
        /// <remarks/>
        public string pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityReferenceOfaeropuerto : EntityReference {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityReferenceOfavion : EntityReference {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void buscarVuelosCompletedEventHandler(object sender, buscarVuelosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarVuelosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarVuelosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public vuelo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((vuelo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void buscarVuelos2CompletedEventHandler(object sender, buscarVuelos2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarVuelos2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarVuelos2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public vuelo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((vuelo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void listaAeropuertosCompletedEventHandler(object sender, listaAeropuertosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listaAeropuertosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listaAeropuertosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public aeropuerto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((aeropuerto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void capacidadVueloCompletedEventHandler(object sender, capacidadVueloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class capacidadVueloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal capacidadVueloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public avion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((avion[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591