//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("AirlineModel", "FK_Vuelo_Aerolinea", "aerolinea", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FlightService.aerolinea), "vuelo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FlightService.vuelo), true)]
[assembly: EdmRelationshipAttribute("AirlineModel", "FK_Vuelo_AeropuertoDestino", "aeropuerto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FlightService.aeropuerto), "vuelo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FlightService.vuelo), true)]
[assembly: EdmRelationshipAttribute("AirlineModel", "FK_Vuelo_AeropuertoOrigen", "aeropuerto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FlightService.aeropuerto), "vuelo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FlightService.vuelo), true)]
[assembly: EdmRelationshipAttribute("AirlineModel", "FK_Configuracion_Avion", "avion", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FlightService.avion), "configuracion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FlightService.configuracion), true)]
[assembly: EdmRelationshipAttribute("AirlineModel", "FK_Vuelo_Avion", "avion", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FlightService.avion), "vuelo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FlightService.vuelo), true)]
[assembly: EdmRelationshipAttribute("AirlineModel", "FK_Configuracion_Clase", "clases", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FlightService.clases), "configuracion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FlightService.configuracion), true)]

#endregion

namespace FlightService
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class AirlineEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto AirlineEntities usando la cadena de conexión encontrada en la sección 'AirlineEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public AirlineEntities() : base("name=AirlineEntities", "AirlineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto AirlineEntities.
        /// </summary>
        public AirlineEntities(string connectionString) : base(connectionString, "AirlineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto AirlineEntities.
        /// </summary>
        public AirlineEntities(EntityConnection connection) : base(connection, "AirlineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<aerolinea> aerolinea
        {
            get
            {
                if ((_aerolinea == null))
                {
                    _aerolinea = base.CreateObjectSet<aerolinea>("aerolinea");
                }
                return _aerolinea;
            }
        }
        private ObjectSet<aerolinea> _aerolinea;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<aeropuerto> aeropuerto
        {
            get
            {
                if ((_aeropuerto == null))
                {
                    _aeropuerto = base.CreateObjectSet<aeropuerto>("aeropuerto");
                }
                return _aeropuerto;
            }
        }
        private ObjectSet<aeropuerto> _aeropuerto;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<avion> avion
        {
            get
            {
                if ((_avion == null))
                {
                    _avion = base.CreateObjectSet<avion>("avion");
                }
                return _avion;
            }
        }
        private ObjectSet<avion> _avion;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<clases> clases
        {
            get
            {
                if ((_clases == null))
                {
                    _clases = base.CreateObjectSet<clases>("clases");
                }
                return _clases;
            }
        }
        private ObjectSet<clases> _clases;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<configuracion> configuracion
        {
            get
            {
                if ((_configuracion == null))
                {
                    _configuracion = base.CreateObjectSet<configuracion>("configuracion");
                }
                return _configuracion;
            }
        }
        private ObjectSet<configuracion> _configuracion;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<vuelo> vuelo
        {
            get
            {
                if ((_vuelo == null))
                {
                    _vuelo = base.CreateObjectSet<vuelo>("vuelo");
                }
                return _vuelo;
            }
        }
        private ObjectSet<vuelo> _vuelo;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet aerolinea. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToaerolinea(aerolinea aerolinea)
        {
            base.AddObject("aerolinea", aerolinea);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet aeropuerto. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToaeropuerto(aeropuerto aeropuerto)
        {
            base.AddObject("aeropuerto", aeropuerto);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet avion. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToavion(avion avion)
        {
            base.AddObject("avion", avion);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet clases. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToclases(clases clases)
        {
            base.AddObject("clases", clases);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet configuracion. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToconfiguracion(configuracion configuracion)
        {
            base.AddObject("configuracion", configuracion);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet vuelo. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTovuelo(vuelo vuelo)
        {
            base.AddObject("vuelo", vuelo);
        }

        #endregion
        #region Importaciones de funciones
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="fECHA">No hay documentación de metadatos disponible.</param>
        public ObjectResult<vuelo> LISTVUELOSPORFECHAS3(global::System.String fECHA)
        {
            ObjectParameter fECHAParameter;
            if (fECHA != null)
            {
                fECHAParameter = new ObjectParameter("FECHA", fECHA);
            }
            else
            {
                fECHAParameter = new ObjectParameter("FECHA", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<vuelo>("LISTVUELOSPORFECHAS3", fECHAParameter);
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="fECHA">No hay documentación de metadatos disponible.</param>
        public ObjectResult<vuelo> LISTVUELOSPORFECHAS3(global::System.String fECHA, MergeOption mergeOption)
        {
            ObjectParameter fECHAParameter;
            if (fECHA != null)
            {
                fECHAParameter = new ObjectParameter("FECHA", fECHA);
            }
            else
            {
                fECHAParameter = new ObjectParameter("FECHA", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<vuelo>("LISTVUELOSPORFECHAS3", mergeOption, fECHAParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AirlineModel", Name="aerolinea")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class aerolinea : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto aerolinea.
        /// </summary>
        /// <param name="codigo">Valor inicial de la propiedad codigo.</param>
        /// <param name="descripcion">Valor inicial de la propiedad descripcion.</param>
        public static aerolinea Createaerolinea(global::System.String codigo, global::System.String descripcion)
        {
            aerolinea aerolinea = new aerolinea();
            aerolinea.codigo = codigo;
            aerolinea.descripcion = descripcion;
            return aerolinea;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AirlineModel", "FK_Vuelo_Aerolinea", "vuelo")]
        public EntityCollection<vuelo> vuelo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<vuelo>("AirlineModel.FK_Vuelo_Aerolinea", "vuelo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<vuelo>("AirlineModel.FK_Vuelo_Aerolinea", "vuelo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AirlineModel", Name="aeropuerto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class aeropuerto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto aeropuerto.
        /// </summary>
        /// <param name="codigo">Valor inicial de la propiedad codigo.</param>
        /// <param name="descripcion">Valor inicial de la propiedad descripcion.</param>
        /// <param name="ciudad">Valor inicial de la propiedad ciudad.</param>
        /// <param name="pais">Valor inicial de la propiedad pais.</param>
        /// <param name="direccion">Valor inicial de la propiedad direccion.</param>
        public static aeropuerto Createaeropuerto(global::System.String codigo, global::System.String descripcion, global::System.String ciudad, global::System.String pais, global::System.String direccion)
        {
            aeropuerto aeropuerto = new aeropuerto();
            aeropuerto.codigo = codigo;
            aeropuerto.descripcion = descripcion;
            aeropuerto.ciudad = ciudad;
            aeropuerto.pais = pais;
            aeropuerto.direccion = direccion;
            return aeropuerto;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ciudad
        {
            get
            {
                return _ciudad;
            }
            set
            {
                OnciudadChanging(value);
                ReportPropertyChanging("ciudad");
                _ciudad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ciudad");
                OnciudadChanged();
            }
        }
        private global::System.String _ciudad;
        partial void OnciudadChanging(global::System.String value);
        partial void OnciudadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String pais
        {
            get
            {
                return _pais;
            }
            set
            {
                OnpaisChanging(value);
                ReportPropertyChanging("pais");
                _pais = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("pais");
                OnpaisChanged();
            }
        }
        private global::System.String _pais;
        partial void OnpaisChanging(global::System.String value);
        partial void OnpaisChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String direccion
        {
            get
            {
                return _direccion;
            }
            set
            {
                OndireccionChanging(value);
                ReportPropertyChanging("direccion");
                _direccion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("direccion");
                OndireccionChanged();
            }
        }
        private global::System.String _direccion;
        partial void OndireccionChanging(global::System.String value);
        partial void OndireccionChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AirlineModel", "FK_Vuelo_AeropuertoDestino", "vuelo")]
        public EntityCollection<vuelo> vuelo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<vuelo>("AirlineModel.FK_Vuelo_AeropuertoDestino", "vuelo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<vuelo>("AirlineModel.FK_Vuelo_AeropuertoDestino", "vuelo", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AirlineModel", "FK_Vuelo_AeropuertoOrigen", "vuelo")]
        public EntityCollection<vuelo> vuelo1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<vuelo>("AirlineModel.FK_Vuelo_AeropuertoOrigen", "vuelo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<vuelo>("AirlineModel.FK_Vuelo_AeropuertoOrigen", "vuelo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AirlineModel", Name="avion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class avion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto avion.
        /// </summary>
        /// <param name="codigo">Valor inicial de la propiedad codigo.</param>
        /// <param name="descripcion">Valor inicial de la propiedad descripcion.</param>
        /// <param name="capacidad">Valor inicial de la propiedad capacidad.</param>
        public static avion Createavion(global::System.String codigo, global::System.String descripcion, global::System.Int32 capacidad)
        {
            avion avion = new avion();
            avion.codigo = codigo;
            avion.descripcion = descripcion;
            avion.capacidad = capacidad;
            return avion;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 capacidad
        {
            get
            {
                return _capacidad;
            }
            set
            {
                OncapacidadChanging(value);
                ReportPropertyChanging("capacidad");
                _capacidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("capacidad");
                OncapacidadChanged();
            }
        }
        private global::System.Int32 _capacidad;
        partial void OncapacidadChanging(global::System.Int32 value);
        partial void OncapacidadChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AirlineModel", "FK_Configuracion_Avion", "configuracion")]
        public EntityCollection<configuracion> configuracion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<configuracion>("AirlineModel.FK_Configuracion_Avion", "configuracion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<configuracion>("AirlineModel.FK_Configuracion_Avion", "configuracion", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AirlineModel", "FK_Vuelo_Avion", "vuelo")]
        public EntityCollection<vuelo> vuelo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<vuelo>("AirlineModel.FK_Vuelo_Avion", "vuelo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<vuelo>("AirlineModel.FK_Vuelo_Avion", "vuelo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AirlineModel", Name="clases")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class clases : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto clases.
        /// </summary>
        /// <param name="codigo">Valor inicial de la propiedad codigo.</param>
        public static clases Createclases(global::System.String codigo)
        {
            clases clases = new clases();
            clases.codigo = codigo;
            return clases;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AirlineModel", "FK_Configuracion_Clase", "configuracion")]
        public EntityCollection<configuracion> configuracion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<configuracion>("AirlineModel.FK_Configuracion_Clase", "configuracion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<configuracion>("AirlineModel.FK_Configuracion_Clase", "configuracion", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AirlineModel", Name="configuracion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class configuracion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto configuracion.
        /// </summary>
        /// <param name="avion">Valor inicial de la propiedad avion.</param>
        /// <param name="clase">Valor inicial de la propiedad clase.</param>
        public static configuracion Createconfiguracion(global::System.String avion, global::System.String clase)
        {
            configuracion configuracion = new configuracion();
            configuracion.avion = avion;
            configuracion.clase = clase;
            return configuracion;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String avion
        {
            get
            {
                return _avion;
            }
            set
            {
                if (_avion != value)
                {
                    OnavionChanging(value);
                    ReportPropertyChanging("avion");
                    _avion = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("avion");
                    OnavionChanged();
                }
            }
        }
        private global::System.String _avion;
        partial void OnavionChanging(global::System.String value);
        partial void OnavionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String clase
        {
            get
            {
                return _clase;
            }
            set
            {
                if (_clase != value)
                {
                    OnclaseChanging(value);
                    ReportPropertyChanging("clase");
                    _clase = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("clase");
                    OnclaseChanged();
                }
            }
        }
        private global::System.String _clase;
        partial void OnclaseChanging(global::System.String value);
        partial void OnclaseChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> capacidad
        {
            get
            {
                return _capacidad;
            }
            set
            {
                OncapacidadChanging(value);
                ReportPropertyChanging("capacidad");
                _capacidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("capacidad");
                OncapacidadChanged();
            }
        }
        private Nullable<global::System.Int32> _capacidad;
        partial void OncapacidadChanging(Nullable<global::System.Int32> value);
        partial void OncapacidadChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AirlineModel", "FK_Configuracion_Avion", "avion")]
        public avion avion1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<avion>("AirlineModel.FK_Configuracion_Avion", "avion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<avion>("AirlineModel.FK_Configuracion_Avion", "avion").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<avion> avion1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<avion>("AirlineModel.FK_Configuracion_Avion", "avion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<avion>("AirlineModel.FK_Configuracion_Avion", "avion", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AirlineModel", "FK_Configuracion_Clase", "clases")]
        public clases clases
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<clases>("AirlineModel.FK_Configuracion_Clase", "clases").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<clases>("AirlineModel.FK_Configuracion_Clase", "clases").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<clases> clasesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<clases>("AirlineModel.FK_Configuracion_Clase", "clases");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<clases>("AirlineModel.FK_Configuracion_Clase", "clases", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AirlineModel", Name="vuelo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vuelo : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto vuelo.
        /// </summary>
        /// <param name="codigo">Valor inicial de la propiedad codigo.</param>
        /// <param name="aerolinea">Valor inicial de la propiedad aerolinea.</param>
        /// <param name="origen">Valor inicial de la propiedad origen.</param>
        /// <param name="destino">Valor inicial de la propiedad destino.</param>
        /// <param name="avion">Valor inicial de la propiedad avion.</param>
        /// <param name="salida">Valor inicial de la propiedad salida.</param>
        /// <param name="llegada">Valor inicial de la propiedad llegada.</param>
        public static vuelo Createvuelo(global::System.String codigo, global::System.String aerolinea, global::System.String origen, global::System.String destino, global::System.String avion, global::System.DateTime salida, global::System.DateTime llegada)
        {
            vuelo vuelo = new vuelo();
            vuelo.codigo = codigo;
            vuelo.aerolinea = aerolinea;
            vuelo.origen = origen;
            vuelo.destino = destino;
            vuelo.avion = avion;
            vuelo.salida = salida;
            vuelo.llegada = llegada;
            return vuelo;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String aerolinea
        {
            get
            {
                return _aerolinea;
            }
            set
            {
                OnaerolineaChanging(value);
                ReportPropertyChanging("aerolinea");
                _aerolinea = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("aerolinea");
                OnaerolineaChanged();
            }
        }
        private global::System.String _aerolinea;
        partial void OnaerolineaChanging(global::System.String value);
        partial void OnaerolineaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String origen
        {
            get
            {
                return _origen;
            }
            set
            {
                OnorigenChanging(value);
                ReportPropertyChanging("origen");
                _origen = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("origen");
                OnorigenChanged();
            }
        }
        private global::System.String _origen;
        partial void OnorigenChanging(global::System.String value);
        partial void OnorigenChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String destino
        {
            get
            {
                return _destino;
            }
            set
            {
                OndestinoChanging(value);
                ReportPropertyChanging("destino");
                _destino = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("destino");
                OndestinoChanged();
            }
        }
        private global::System.String _destino;
        partial void OndestinoChanging(global::System.String value);
        partial void OndestinoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String avion
        {
            get
            {
                return _avion;
            }
            set
            {
                OnavionChanging(value);
                ReportPropertyChanging("avion");
                _avion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("avion");
                OnavionChanged();
            }
        }
        private global::System.String _avion;
        partial void OnavionChanging(global::System.String value);
        partial void OnavionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime salida
        {
            get
            {
                return _salida;
            }
            set
            {
                OnsalidaChanging(value);
                ReportPropertyChanging("salida");
                _salida = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("salida");
                OnsalidaChanged();
            }
        }
        private global::System.DateTime _salida;
        partial void OnsalidaChanging(global::System.DateTime value);
        partial void OnsalidaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime llegada
        {
            get
            {
                return _llegada;
            }
            set
            {
                OnllegadaChanging(value);
                ReportPropertyChanging("llegada");
                _llegada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("llegada");
                OnllegadaChanged();
            }
        }
        private global::System.DateTime _llegada;
        partial void OnllegadaChanging(global::System.DateTime value);
        partial void OnllegadaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.SByte> estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private Nullable<global::System.SByte> _estado;
        partial void OnestadoChanging(Nullable<global::System.SByte> value);
        partial void OnestadoChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AirlineModel", "FK_Vuelo_Aerolinea", "aerolinea")]
        public aerolinea aerolinea1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aerolinea>("AirlineModel.FK_Vuelo_Aerolinea", "aerolinea").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aerolinea>("AirlineModel.FK_Vuelo_Aerolinea", "aerolinea").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<aerolinea> aerolinea1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aerolinea>("AirlineModel.FK_Vuelo_Aerolinea", "aerolinea");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<aerolinea>("AirlineModel.FK_Vuelo_Aerolinea", "aerolinea", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AirlineModel", "FK_Vuelo_AeropuertoDestino", "aeropuerto")]
        public aeropuerto aeropuerto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aeropuerto>("AirlineModel.FK_Vuelo_AeropuertoDestino", "aeropuerto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aeropuerto>("AirlineModel.FK_Vuelo_AeropuertoDestino", "aeropuerto").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<aeropuerto> aeropuertoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aeropuerto>("AirlineModel.FK_Vuelo_AeropuertoDestino", "aeropuerto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<aeropuerto>("AirlineModel.FK_Vuelo_AeropuertoDestino", "aeropuerto", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AirlineModel", "FK_Vuelo_AeropuertoOrigen", "aeropuerto")]
        public aeropuerto aeropuerto1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aeropuerto>("AirlineModel.FK_Vuelo_AeropuertoOrigen", "aeropuerto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aeropuerto>("AirlineModel.FK_Vuelo_AeropuertoOrigen", "aeropuerto").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<aeropuerto> aeropuerto1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aeropuerto>("AirlineModel.FK_Vuelo_AeropuertoOrigen", "aeropuerto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<aeropuerto>("AirlineModel.FK_Vuelo_AeropuertoOrigen", "aeropuerto", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AirlineModel", "FK_Vuelo_Avion", "avion")]
        public avion avion1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<avion>("AirlineModel.FK_Vuelo_Avion", "avion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<avion>("AirlineModel.FK_Vuelo_Avion", "avion").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<avion> avion1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<avion>("AirlineModel.FK_Vuelo_Avion", "avion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<avion>("AirlineModel.FK_Vuelo_Avion", "avion", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
