//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("AirlineModel", "FK_Vuelo_Aerolinea", "aerolinea", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FlightService.aerolinea), "vuelo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FlightService.vuelo), true)]
[assembly: EdmRelationshipAttribute("AirlineModel", "FK_Vuelo_AeropuertoDestino", "aeropuerto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FlightService.aeropuerto), "vuelo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FlightService.vuelo), true)]
[assembly: EdmRelationshipAttribute("AirlineModel", "FK_Vuelo_AeropuertoOrigen", "aeropuerto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FlightService.aeropuerto), "vuelo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FlightService.vuelo), true)]
[assembly: EdmRelationshipAttribute("AirlineModel", "FK_Configuracion_Avion", "avion", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FlightService.avion), "configuracion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FlightService.configuracion), true)]
[assembly: EdmRelationshipAttribute("AirlineModel", "FK_Vuelo_Avion", "avion", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FlightService.avion), "vuelo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FlightService.vuelo), true)]
[assembly: EdmRelationshipAttribute("AirlineModel", "FK_Configuracion_Clase", "clases", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FlightService.clases), "configuracion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FlightService.configuracion), true)]

#endregion

namespace FlightService
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AirlineEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AirlineEntities object using the connection string found in the 'AirlineEntities' section of the application configuration file.
        /// </summary>
        public AirlineEntities() : base("name=AirlineEntities", "AirlineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AirlineEntities object.
        /// </summary>
        public AirlineEntities(string connectionString) : base(connectionString, "AirlineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AirlineEntities object.
        /// </summary>
        public AirlineEntities(EntityConnection connection) : base(connection, "AirlineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<aerolinea> aerolinea
        {
            get
            {
                if ((_aerolinea == null))
                {
                    _aerolinea = base.CreateObjectSet<aerolinea>("aerolinea");
                }
                return _aerolinea;
            }
        }
        private ObjectSet<aerolinea> _aerolinea;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<aeropuerto> aeropuerto
        {
            get
            {
                if ((_aeropuerto == null))
                {
                    _aeropuerto = base.CreateObjectSet<aeropuerto>("aeropuerto");
                }
                return _aeropuerto;
            }
        }
        private ObjectSet<aeropuerto> _aeropuerto;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<avion> avion
        {
            get
            {
                if ((_avion == null))
                {
                    _avion = base.CreateObjectSet<avion>("avion");
                }
                return _avion;
            }
        }
        private ObjectSet<avion> _avion;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<clases> clases
        {
            get
            {
                if ((_clases == null))
                {
                    _clases = base.CreateObjectSet<clases>("clases");
                }
                return _clases;
            }
        }
        private ObjectSet<clases> _clases;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<configuracion> configuracion
        {
            get
            {
                if ((_configuracion == null))
                {
                    _configuracion = base.CreateObjectSet<configuracion>("configuracion");
                }
                return _configuracion;
            }
        }
        private ObjectSet<configuracion> _configuracion;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vuelo> vuelo
        {
            get
            {
                if ((_vuelo == null))
                {
                    _vuelo = base.CreateObjectSet<vuelo>("vuelo");
                }
                return _vuelo;
            }
        }
        private ObjectSet<vuelo> _vuelo;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the aerolinea EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaerolinea(aerolinea aerolinea)
        {
            base.AddObject("aerolinea", aerolinea);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the aeropuerto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaeropuerto(aeropuerto aeropuerto)
        {
            base.AddObject("aeropuerto", aeropuerto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the avion EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToavion(avion avion)
        {
            base.AddObject("avion", avion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the clases EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToclases(clases clases)
        {
            base.AddObject("clases", clases);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the configuracion EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToconfiguracion(configuracion configuracion)
        {
            base.AddObject("configuracion", configuracion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vuelo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovuelo(vuelo vuelo)
        {
            base.AddObject("vuelo", vuelo);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AirlineModel", Name="aerolinea")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class aerolinea : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new aerolinea object.
        /// </summary>
        /// <param name="codigo">Initial value of the codigo property.</param>
        /// <param name="descripcion">Initial value of the descripcion property.</param>
        public static aerolinea Createaerolinea(global::System.String codigo, global::System.String descripcion)
        {
            aerolinea aerolinea = new aerolinea();
            aerolinea.codigo = codigo;
            aerolinea.descripcion = descripcion;
            return aerolinea;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AirlineModel", "FK_Vuelo_Aerolinea", "vuelo")]
        public EntityCollection<vuelo> vuelo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<vuelo>("AirlineModel.FK_Vuelo_Aerolinea", "vuelo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<vuelo>("AirlineModel.FK_Vuelo_Aerolinea", "vuelo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AirlineModel", Name="aeropuerto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class aeropuerto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new aeropuerto object.
        /// </summary>
        /// <param name="codigo">Initial value of the codigo property.</param>
        /// <param name="descripcion">Initial value of the descripcion property.</param>
        /// <param name="ciudad">Initial value of the ciudad property.</param>
        /// <param name="pais">Initial value of the pais property.</param>
        /// <param name="direccion">Initial value of the direccion property.</param>
        public static aeropuerto Createaeropuerto(global::System.String codigo, global::System.String descripcion, global::System.String ciudad, global::System.String pais, global::System.String direccion)
        {
            aeropuerto aeropuerto = new aeropuerto();
            aeropuerto.codigo = codigo;
            aeropuerto.descripcion = descripcion;
            aeropuerto.ciudad = ciudad;
            aeropuerto.pais = pais;
            aeropuerto.direccion = direccion;
            return aeropuerto;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ciudad
        {
            get
            {
                return _ciudad;
            }
            set
            {
                OnciudadChanging(value);
                ReportPropertyChanging("ciudad");
                _ciudad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ciudad");
                OnciudadChanged();
            }
        }
        private global::System.String _ciudad;
        partial void OnciudadChanging(global::System.String value);
        partial void OnciudadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String pais
        {
            get
            {
                return _pais;
            }
            set
            {
                OnpaisChanging(value);
                ReportPropertyChanging("pais");
                _pais = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("pais");
                OnpaisChanged();
            }
        }
        private global::System.String _pais;
        partial void OnpaisChanging(global::System.String value);
        partial void OnpaisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String direccion
        {
            get
            {
                return _direccion;
            }
            set
            {
                OndireccionChanging(value);
                ReportPropertyChanging("direccion");
                _direccion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("direccion");
                OndireccionChanged();
            }
        }
        private global::System.String _direccion;
        partial void OndireccionChanging(global::System.String value);
        partial void OndireccionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AirlineModel", "FK_Vuelo_AeropuertoDestino", "vuelo")]
        public EntityCollection<vuelo> vuelo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<vuelo>("AirlineModel.FK_Vuelo_AeropuertoDestino", "vuelo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<vuelo>("AirlineModel.FK_Vuelo_AeropuertoDestino", "vuelo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AirlineModel", "FK_Vuelo_AeropuertoOrigen", "vuelo")]
        public EntityCollection<vuelo> vuelo1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<vuelo>("AirlineModel.FK_Vuelo_AeropuertoOrigen", "vuelo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<vuelo>("AirlineModel.FK_Vuelo_AeropuertoOrigen", "vuelo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AirlineModel", Name="avion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class avion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new avion object.
        /// </summary>
        /// <param name="codigo">Initial value of the codigo property.</param>
        /// <param name="descripcion">Initial value of the descripcion property.</param>
        /// <param name="capacidad">Initial value of the capacidad property.</param>
        public static avion Createavion(global::System.String codigo, global::System.String descripcion, global::System.Int32 capacidad)
        {
            avion avion = new avion();
            avion.codigo = codigo;
            avion.descripcion = descripcion;
            avion.capacidad = capacidad;
            return avion;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 capacidad
        {
            get
            {
                return _capacidad;
            }
            set
            {
                OncapacidadChanging(value);
                ReportPropertyChanging("capacidad");
                _capacidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("capacidad");
                OncapacidadChanged();
            }
        }
        private global::System.Int32 _capacidad;
        partial void OncapacidadChanging(global::System.Int32 value);
        partial void OncapacidadChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AirlineModel", "FK_Configuracion_Avion", "configuracion")]
        public EntityCollection<configuracion> configuracion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<configuracion>("AirlineModel.FK_Configuracion_Avion", "configuracion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<configuracion>("AirlineModel.FK_Configuracion_Avion", "configuracion", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AirlineModel", "FK_Vuelo_Avion", "vuelo")]
        public EntityCollection<vuelo> vuelo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<vuelo>("AirlineModel.FK_Vuelo_Avion", "vuelo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<vuelo>("AirlineModel.FK_Vuelo_Avion", "vuelo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AirlineModel", Name="clases")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class clases : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new clases object.
        /// </summary>
        /// <param name="codigo">Initial value of the codigo property.</param>
        public static clases Createclases(global::System.String codigo)
        {
            clases clases = new clases();
            clases.codigo = codigo;
            return clases;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AirlineModel", "FK_Configuracion_Clase", "configuracion")]
        public EntityCollection<configuracion> configuracion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<configuracion>("AirlineModel.FK_Configuracion_Clase", "configuracion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<configuracion>("AirlineModel.FK_Configuracion_Clase", "configuracion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AirlineModel", Name="configuracion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class configuracion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new configuracion object.
        /// </summary>
        /// <param name="avion">Initial value of the avion property.</param>
        /// <param name="clase">Initial value of the clase property.</param>
        public static configuracion Createconfiguracion(global::System.String avion, global::System.String clase)
        {
            configuracion configuracion = new configuracion();
            configuracion.avion = avion;
            configuracion.clase = clase;
            return configuracion;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String avion
        {
            get
            {
                return _avion;
            }
            set
            {
                if (_avion != value)
                {
                    OnavionChanging(value);
                    ReportPropertyChanging("avion");
                    _avion = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("avion");
                    OnavionChanged();
                }
            }
        }
        private global::System.String _avion;
        partial void OnavionChanging(global::System.String value);
        partial void OnavionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String clase
        {
            get
            {
                return _clase;
            }
            set
            {
                if (_clase != value)
                {
                    OnclaseChanging(value);
                    ReportPropertyChanging("clase");
                    _clase = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("clase");
                    OnclaseChanged();
                }
            }
        }
        private global::System.String _clase;
        partial void OnclaseChanging(global::System.String value);
        partial void OnclaseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> capacidad
        {
            get
            {
                return _capacidad;
            }
            set
            {
                OncapacidadChanging(value);
                ReportPropertyChanging("capacidad");
                _capacidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("capacidad");
                OncapacidadChanged();
            }
        }
        private Nullable<global::System.Int32> _capacidad;
        partial void OncapacidadChanging(Nullable<global::System.Int32> value);
        partial void OncapacidadChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AirlineModel", "FK_Configuracion_Avion", "avion")]
        public avion avion1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<avion>("AirlineModel.FK_Configuracion_Avion", "avion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<avion>("AirlineModel.FK_Configuracion_Avion", "avion").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<avion> avion1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<avion>("AirlineModel.FK_Configuracion_Avion", "avion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<avion>("AirlineModel.FK_Configuracion_Avion", "avion", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AirlineModel", "FK_Configuracion_Clase", "clases")]
        public clases clases
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<clases>("AirlineModel.FK_Configuracion_Clase", "clases").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<clases>("AirlineModel.FK_Configuracion_Clase", "clases").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<clases> clasesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<clases>("AirlineModel.FK_Configuracion_Clase", "clases");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<clases>("AirlineModel.FK_Configuracion_Clase", "clases", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AirlineModel", Name="vuelo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vuelo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vuelo object.
        /// </summary>
        /// <param name="codigo">Initial value of the codigo property.</param>
        /// <param name="aerolinea">Initial value of the aerolinea property.</param>
        /// <param name="origen">Initial value of the origen property.</param>
        /// <param name="destino">Initial value of the destino property.</param>
        /// <param name="avion">Initial value of the avion property.</param>
        /// <param name="salida">Initial value of the salida property.</param>
        /// <param name="llegada">Initial value of the llegada property.</param>
        public static vuelo Createvuelo(global::System.String codigo, global::System.String aerolinea, global::System.String origen, global::System.String destino, global::System.String avion, global::System.DateTime salida, global::System.DateTime llegada)
        {
            vuelo vuelo = new vuelo();
            vuelo.codigo = codigo;
            vuelo.aerolinea = aerolinea;
            vuelo.origen = origen;
            vuelo.destino = destino;
            vuelo.avion = avion;
            vuelo.salida = salida;
            vuelo.llegada = llegada;
            return vuelo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String aerolinea
        {
            get
            {
                return _aerolinea;
            }
            set
            {
                OnaerolineaChanging(value);
                ReportPropertyChanging("aerolinea");
                _aerolinea = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("aerolinea");
                OnaerolineaChanged();
            }
        }
        private global::System.String _aerolinea;
        partial void OnaerolineaChanging(global::System.String value);
        partial void OnaerolineaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String origen
        {
            get
            {
                return _origen;
            }
            set
            {
                OnorigenChanging(value);
                ReportPropertyChanging("origen");
                _origen = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("origen");
                OnorigenChanged();
            }
        }
        private global::System.String _origen;
        partial void OnorigenChanging(global::System.String value);
        partial void OnorigenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String destino
        {
            get
            {
                return _destino;
            }
            set
            {
                OndestinoChanging(value);
                ReportPropertyChanging("destino");
                _destino = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("destino");
                OndestinoChanged();
            }
        }
        private global::System.String _destino;
        partial void OndestinoChanging(global::System.String value);
        partial void OndestinoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String avion
        {
            get
            {
                return _avion;
            }
            set
            {
                OnavionChanging(value);
                ReportPropertyChanging("avion");
                _avion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("avion");
                OnavionChanged();
            }
        }
        private global::System.String _avion;
        partial void OnavionChanging(global::System.String value);
        partial void OnavionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime salida
        {
            get
            {
                return _salida;
            }
            set
            {
                OnsalidaChanging(value);
                ReportPropertyChanging("salida");
                _salida = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("salida");
                OnsalidaChanged();
            }
        }
        private global::System.DateTime _salida;
        partial void OnsalidaChanging(global::System.DateTime value);
        partial void OnsalidaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime llegada
        {
            get
            {
                return _llegada;
            }
            set
            {
                OnllegadaChanging(value);
                ReportPropertyChanging("llegada");
                _llegada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("llegada");
                OnllegadaChanged();
            }
        }
        private global::System.DateTime _llegada;
        partial void OnllegadaChanging(global::System.DateTime value);
        partial void OnllegadaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.SByte> estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private Nullable<global::System.SByte> _estado;
        partial void OnestadoChanging(Nullable<global::System.SByte> value);
        partial void OnestadoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AirlineModel", "FK_Vuelo_Aerolinea", "aerolinea")]
        public aerolinea aerolinea1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aerolinea>("AirlineModel.FK_Vuelo_Aerolinea", "aerolinea").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aerolinea>("AirlineModel.FK_Vuelo_Aerolinea", "aerolinea").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<aerolinea> aerolinea1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aerolinea>("AirlineModel.FK_Vuelo_Aerolinea", "aerolinea");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<aerolinea>("AirlineModel.FK_Vuelo_Aerolinea", "aerolinea", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AirlineModel", "FK_Vuelo_AeropuertoDestino", "aeropuerto")]
        public aeropuerto aeropuerto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aeropuerto>("AirlineModel.FK_Vuelo_AeropuertoDestino", "aeropuerto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aeropuerto>("AirlineModel.FK_Vuelo_AeropuertoDestino", "aeropuerto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<aeropuerto> aeropuertoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aeropuerto>("AirlineModel.FK_Vuelo_AeropuertoDestino", "aeropuerto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<aeropuerto>("AirlineModel.FK_Vuelo_AeropuertoDestino", "aeropuerto", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AirlineModel", "FK_Vuelo_AeropuertoOrigen", "aeropuerto")]
        public aeropuerto aeropuerto1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aeropuerto>("AirlineModel.FK_Vuelo_AeropuertoOrigen", "aeropuerto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aeropuerto>("AirlineModel.FK_Vuelo_AeropuertoOrigen", "aeropuerto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<aeropuerto> aeropuerto1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aeropuerto>("AirlineModel.FK_Vuelo_AeropuertoOrigen", "aeropuerto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<aeropuerto>("AirlineModel.FK_Vuelo_AeropuertoOrigen", "aeropuerto", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AirlineModel", "FK_Vuelo_Avion", "avion")]
        public avion avion1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<avion>("AirlineModel.FK_Vuelo_Avion", "avion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<avion>("AirlineModel.FK_Vuelo_Avion", "avion").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<avion> avion1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<avion>("AirlineModel.FK_Vuelo_Avion", "avion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<avion>("AirlineModel.FK_Vuelo_Avion", "avion", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
