//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("airlineModel", "FK_Vuelo_Aerolinea", "aerolinea", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FlightService.aerolinea), "vuelo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FlightService.vuelo), true)]
[assembly: EdmRelationshipAttribute("airlineModel", "FK_Vuelo_AeropuertoDestino", "aeropuerto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FlightService.aeropuerto), "vuelo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FlightService.vuelo), true)]
[assembly: EdmRelationshipAttribute("airlineModel", "FK_Vuelo_AeropuertoOrigen", "aeropuerto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FlightService.aeropuerto), "vuelo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FlightService.vuelo), true)]
[assembly: EdmRelationshipAttribute("airlineModel", "FK_Configuracion_Avion", "avion", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FlightService.avion), "configuracion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FlightService.configuracion), true)]
[assembly: EdmRelationshipAttribute("airlineModel", "FK_Vuelo_Avion", "avion", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FlightService.avion), "vuelo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FlightService.vuelo), true)]
[assembly: EdmRelationshipAttribute("airlineModel", "FK_Configuracion_Clase", "clases", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FlightService.clas), "configuracion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FlightService.configuracion), true)]

#endregion

namespace FlightService
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class airlineEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new airlineEntities object using the connection string found in the 'airlineEntities' section of the application configuration file.
        /// </summary>
        public airlineEntities() : base("name=airlineEntities", "airlineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new airlineEntities object.
        /// </summary>
        public airlineEntities(string connectionString) : base(connectionString, "airlineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new airlineEntities object.
        /// </summary>
        public airlineEntities(EntityConnection connection) : base(connection, "airlineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<aerolinea> aerolineas
        {
            get
            {
                if ((_aerolineas == null))
                {
                    _aerolineas = base.CreateObjectSet<aerolinea>("aerolineas");
                }
                return _aerolineas;
            }
        }
        private ObjectSet<aerolinea> _aerolineas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<aeropuerto> aeropuertoes
        {
            get
            {
                if ((_aeropuertoes == null))
                {
                    _aeropuertoes = base.CreateObjectSet<aeropuerto>("aeropuertoes");
                }
                return _aeropuertoes;
            }
        }
        private ObjectSet<aeropuerto> _aeropuertoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<avion> avions
        {
            get
            {
                if ((_avions == null))
                {
                    _avions = base.CreateObjectSet<avion>("avions");
                }
                return _avions;
            }
        }
        private ObjectSet<avion> _avions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<clas> clases
        {
            get
            {
                if ((_clases == null))
                {
                    _clases = base.CreateObjectSet<clas>("clases");
                }
                return _clases;
            }
        }
        private ObjectSet<clas> _clases;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<configuracion> configuracions
        {
            get
            {
                if ((_configuracions == null))
                {
                    _configuracions = base.CreateObjectSet<configuracion>("configuracions");
                }
                return _configuracions;
            }
        }
        private ObjectSet<configuracion> _configuracions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<usuario> usuarios
        {
            get
            {
                if ((_usuarios == null))
                {
                    _usuarios = base.CreateObjectSet<usuario>("usuarios");
                }
                return _usuarios;
            }
        }
        private ObjectSet<usuario> _usuarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vuelo> vueloes
        {
            get
            {
                if ((_vueloes == null))
                {
                    _vueloes = base.CreateObjectSet<vuelo>("vueloes");
                }
                return _vueloes;
            }
        }
        private ObjectSet<vuelo> _vueloes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the aerolineas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaerolineas(aerolinea aerolinea)
        {
            base.AddObject("aerolineas", aerolinea);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the aeropuertoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaeropuertoes(aeropuerto aeropuerto)
        {
            base.AddObject("aeropuertoes", aeropuerto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the avions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToavions(avion avion)
        {
            base.AddObject("avions", avion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the clases EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToclases(clas clas)
        {
            base.AddObject("clases", clas);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the configuracions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToconfiguracions(configuracion configuracion)
        {
            base.AddObject("configuracions", configuracion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousuarios(usuario usuario)
        {
            base.AddObject("usuarios", usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vueloes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovueloes(vuelo vuelo)
        {
            base.AddObject("vueloes", vuelo);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="fECHA">No Metadata Documentation available.</param>
        public ObjectResult<vuelo> LISTVUELOSPORFECHAS(global::System.String fECHA)
        {
            ObjectParameter fECHAParameter;
            if (fECHA != null)
            {
                fECHAParameter = new ObjectParameter("FECHA", fECHA);
            }
            else
            {
                fECHAParameter = new ObjectParameter("FECHA", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<vuelo>("LISTVUELOSPORFECHAS", fECHAParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="fECHA">No Metadata Documentation available.</param>
        public ObjectResult<vuelo> LISTVUELOSPORFECHAS(global::System.String fECHA, MergeOption mergeOption)
        {
            ObjectParameter fECHAParameter;
            if (fECHA != null)
            {
                fECHAParameter = new ObjectParameter("FECHA", fECHA);
            }
            else
            {
                fECHAParameter = new ObjectParameter("FECHA", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<vuelo>("LISTVUELOSPORFECHAS", mergeOption, fECHAParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="cod_vuelo">No Metadata Documentation available.</param>
        public int sp_capacidad_vuelo(global::System.String cod_vuelo)
        {
            ObjectParameter cod_vueloParameter;
            if (cod_vuelo != null)
            {
                cod_vueloParameter = new ObjectParameter("cod_vuelo", cod_vuelo);
            }
            else
            {
                cod_vueloParameter = new ObjectParameter("cod_vuelo", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("sp_capacidad_vuelo", cod_vueloParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="cod_vuelo">No Metadata Documentation available.</param>
        public ObjectResult<avion> sp_capacidad_vuelo2(global::System.String cod_vuelo)
        {
            ObjectParameter cod_vueloParameter;
            if (cod_vuelo != null)
            {
                cod_vueloParameter = new ObjectParameter("cod_vuelo", cod_vuelo);
            }
            else
            {
                cod_vueloParameter = new ObjectParameter("cod_vuelo", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<avion>("sp_capacidad_vuelo2", cod_vueloParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="cod_vuelo">No Metadata Documentation available.</param>
        public ObjectResult<avion> sp_capacidad_vuelo2(global::System.String cod_vuelo, MergeOption mergeOption)
        {
            ObjectParameter cod_vueloParameter;
            if (cod_vuelo != null)
            {
                cod_vueloParameter = new ObjectParameter("cod_vuelo", cod_vuelo);
            }
            else
            {
                cod_vueloParameter = new ObjectParameter("cod_vuelo", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<avion>("sp_capacidad_vuelo2", mergeOption, cod_vueloParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="airlineModel", Name="aerolinea")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class aerolinea : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new aerolinea object.
        /// </summary>
        /// <param name="codigo">Initial value of the codigo property.</param>
        /// <param name="descripcion">Initial value of the descripcion property.</param>
        public static aerolinea Createaerolinea(global::System.String codigo, global::System.String descripcion)
        {
            aerolinea aerolinea = new aerolinea();
            aerolinea.codigo = codigo;
            aerolinea.descripcion = descripcion;
            return aerolinea;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("airlineModel", "FK_Vuelo_Aerolinea", "vuelo")]
        public EntityCollection<vuelo> vueloes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<vuelo>("airlineModel.FK_Vuelo_Aerolinea", "vuelo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<vuelo>("airlineModel.FK_Vuelo_Aerolinea", "vuelo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="airlineModel", Name="aeropuerto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class aeropuerto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new aeropuerto object.
        /// </summary>
        /// <param name="codigo">Initial value of the codigo property.</param>
        /// <param name="descripcion">Initial value of the descripcion property.</param>
        /// <param name="ciudad">Initial value of the ciudad property.</param>
        /// <param name="pais">Initial value of the pais property.</param>
        /// <param name="direccion">Initial value of the direccion property.</param>
        public static aeropuerto Createaeropuerto(global::System.String codigo, global::System.String descripcion, global::System.String ciudad, global::System.String pais, global::System.String direccion)
        {
            aeropuerto aeropuerto = new aeropuerto();
            aeropuerto.codigo = codigo;
            aeropuerto.descripcion = descripcion;
            aeropuerto.ciudad = ciudad;
            aeropuerto.pais = pais;
            aeropuerto.direccion = direccion;
            return aeropuerto;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ciudad
        {
            get
            {
                return _ciudad;
            }
            set
            {
                OnciudadChanging(value);
                ReportPropertyChanging("ciudad");
                _ciudad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ciudad");
                OnciudadChanged();
            }
        }
        private global::System.String _ciudad;
        partial void OnciudadChanging(global::System.String value);
        partial void OnciudadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String pais
        {
            get
            {
                return _pais;
            }
            set
            {
                OnpaisChanging(value);
                ReportPropertyChanging("pais");
                _pais = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("pais");
                OnpaisChanged();
            }
        }
        private global::System.String _pais;
        partial void OnpaisChanging(global::System.String value);
        partial void OnpaisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String direccion
        {
            get
            {
                return _direccion;
            }
            set
            {
                OndireccionChanging(value);
                ReportPropertyChanging("direccion");
                _direccion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("direccion");
                OndireccionChanged();
            }
        }
        private global::System.String _direccion;
        partial void OndireccionChanging(global::System.String value);
        partial void OndireccionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("airlineModel", "FK_Vuelo_AeropuertoDestino", "vuelo")]
        public EntityCollection<vuelo> vueloes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<vuelo>("airlineModel.FK_Vuelo_AeropuertoDestino", "vuelo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<vuelo>("airlineModel.FK_Vuelo_AeropuertoDestino", "vuelo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("airlineModel", "FK_Vuelo_AeropuertoOrigen", "vuelo")]
        public EntityCollection<vuelo> vueloes1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<vuelo>("airlineModel.FK_Vuelo_AeropuertoOrigen", "vuelo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<vuelo>("airlineModel.FK_Vuelo_AeropuertoOrigen", "vuelo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="airlineModel", Name="avion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class avion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new avion object.
        /// </summary>
        /// <param name="codigo">Initial value of the codigo property.</param>
        /// <param name="descripcion">Initial value of the descripcion property.</param>
        /// <param name="capacidad">Initial value of the capacidad property.</param>
        public static avion Createavion(global::System.Int32 codigo, global::System.String descripcion, global::System.Int32 capacidad)
        {
            avion avion = new avion();
            avion.codigo = codigo;
            avion.descripcion = descripcion;
            avion.capacidad = capacidad;
            return avion;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.Int32 _codigo;
        partial void OncodigoChanging(global::System.Int32 value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 capacidad
        {
            get
            {
                return _capacidad;
            }
            set
            {
                OncapacidadChanging(value);
                ReportPropertyChanging("capacidad");
                _capacidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("capacidad");
                OncapacidadChanged();
            }
        }
        private global::System.Int32 _capacidad;
        partial void OncapacidadChanging(global::System.Int32 value);
        partial void OncapacidadChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("airlineModel", "FK_Configuracion_Avion", "configuracion")]
        public EntityCollection<configuracion> configuracions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<configuracion>("airlineModel.FK_Configuracion_Avion", "configuracion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<configuracion>("airlineModel.FK_Configuracion_Avion", "configuracion", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("airlineModel", "FK_Vuelo_Avion", "vuelo")]
        public EntityCollection<vuelo> vueloes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<vuelo>("airlineModel.FK_Vuelo_Avion", "vuelo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<vuelo>("airlineModel.FK_Vuelo_Avion", "vuelo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="airlineModel", Name="clas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class clas : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new clas object.
        /// </summary>
        /// <param name="codigo">Initial value of the codigo property.</param>
        public static clas Createclas(global::System.Int32 codigo)
        {
            clas clas = new clas();
            clas.codigo = codigo;
            return clas;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.Int32 _codigo;
        partial void OncodigoChanging(global::System.Int32 value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("airlineModel", "FK_Configuracion_Clase", "configuracion")]
        public EntityCollection<configuracion> configuracions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<configuracion>("airlineModel.FK_Configuracion_Clase", "configuracion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<configuracion>("airlineModel.FK_Configuracion_Clase", "configuracion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="airlineModel", Name="configuracion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class configuracion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new configuracion object.
        /// </summary>
        /// <param name="avion">Initial value of the avion property.</param>
        /// <param name="clase">Initial value of the clase property.</param>
        public static configuracion Createconfiguracion(global::System.Int32 avion, global::System.Int32 clase)
        {
            configuracion configuracion = new configuracion();
            configuracion.avion = avion;
            configuracion.clase = clase;
            return configuracion;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 avion
        {
            get
            {
                return _avion;
            }
            set
            {
                if (_avion != value)
                {
                    OnavionChanging(value);
                    ReportPropertyChanging("avion");
                    _avion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("avion");
                    OnavionChanged();
                }
            }
        }
        private global::System.Int32 _avion;
        partial void OnavionChanging(global::System.Int32 value);
        partial void OnavionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 clase
        {
            get
            {
                return _clase;
            }
            set
            {
                if (_clase != value)
                {
                    OnclaseChanging(value);
                    ReportPropertyChanging("clase");
                    _clase = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("clase");
                    OnclaseChanged();
                }
            }
        }
        private global::System.Int32 _clase;
        partial void OnclaseChanging(global::System.Int32 value);
        partial void OnclaseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> capacidad
        {
            get
            {
                return _capacidad;
            }
            set
            {
                OncapacidadChanging(value);
                ReportPropertyChanging("capacidad");
                _capacidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("capacidad");
                OncapacidadChanged();
            }
        }
        private Nullable<global::System.Int32> _capacidad;
        partial void OncapacidadChanging(Nullable<global::System.Int32> value);
        partial void OncapacidadChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("airlineModel", "FK_Configuracion_Avion", "avion")]
        public avion avion1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<avion>("airlineModel.FK_Configuracion_Avion", "avion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<avion>("airlineModel.FK_Configuracion_Avion", "avion").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<avion> avion1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<avion>("airlineModel.FK_Configuracion_Avion", "avion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<avion>("airlineModel.FK_Configuracion_Avion", "avion", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("airlineModel", "FK_Configuracion_Clase", "clases")]
        public clas clas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<clas>("airlineModel.FK_Configuracion_Clase", "clases").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<clas>("airlineModel.FK_Configuracion_Clase", "clases").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<clas> clasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<clas>("airlineModel.FK_Configuracion_Clase", "clases");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<clas>("airlineModel.FK_Configuracion_Clase", "clases", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="airlineModel", Name="usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new usuario object.
        /// </summary>
        /// <param name="nusuario">Initial value of the nusuario property.</param>
        public static usuario Createusuario(global::System.String nusuario)
        {
            usuario usuario = new usuario();
            usuario.nusuario = nusuario;
            return usuario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nusuario
        {
            get
            {
                return _nusuario;
            }
            set
            {
                if (_nusuario != value)
                {
                    OnnusuarioChanging(value);
                    ReportPropertyChanging("nusuario");
                    _nusuario = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("nusuario");
                    OnnusuarioChanged();
                }
            }
        }
        private global::System.String _nusuario;
        partial void OnnusuarioChanging(global::System.String value);
        partial void OnnusuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String clave
        {
            get
            {
                return _clave;
            }
            set
            {
                OnclaveChanging(value);
                ReportPropertyChanging("clave");
                _clave = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("clave");
                OnclaveChanged();
            }
        }
        private global::System.String _clave;
        partial void OnclaveChanging(global::System.String value);
        partial void OnclaveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String apellido
        {
            get
            {
                return _apellido;
            }
            set
            {
                OnapellidoChanging(value);
                ReportPropertyChanging("apellido");
                _apellido = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("apellido");
                OnapellidoChanged();
            }
        }
        private global::System.String _apellido;
        partial void OnapellidoChanging(global::System.String value);
        partial void OnapellidoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="airlineModel", Name="vuelo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vuelo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vuelo object.
        /// </summary>
        /// <param name="codigo">Initial value of the codigo property.</param>
        /// <param name="aerolinea">Initial value of the aerolinea property.</param>
        /// <param name="origen">Initial value of the origen property.</param>
        /// <param name="destino">Initial value of the destino property.</param>
        /// <param name="avion">Initial value of the avion property.</param>
        /// <param name="salida">Initial value of the salida property.</param>
        /// <param name="llegada">Initial value of the llegada property.</param>
        public static vuelo Createvuelo(global::System.Int32 codigo, global::System.String aerolinea, global::System.String origen, global::System.String destino, global::System.Int32 avion, global::System.DateTime salida, global::System.DateTime llegada)
        {
            vuelo vuelo = new vuelo();
            vuelo.codigo = codigo;
            vuelo.aerolinea = aerolinea;
            vuelo.origen = origen;
            vuelo.destino = destino;
            vuelo.avion = avion;
            vuelo.salida = salida;
            vuelo.llegada = llegada;
            return vuelo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.Int32 _codigo;
        partial void OncodigoChanging(global::System.Int32 value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String aerolinea
        {
            get
            {
                return _aerolinea;
            }
            set
            {
                OnaerolineaChanging(value);
                ReportPropertyChanging("aerolinea");
                _aerolinea = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("aerolinea");
                OnaerolineaChanged();
            }
        }
        private global::System.String _aerolinea;
        partial void OnaerolineaChanging(global::System.String value);
        partial void OnaerolineaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String origen
        {
            get
            {
                return _origen;
            }
            set
            {
                OnorigenChanging(value);
                ReportPropertyChanging("origen");
                _origen = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("origen");
                OnorigenChanged();
            }
        }
        private global::System.String _origen;
        partial void OnorigenChanging(global::System.String value);
        partial void OnorigenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String destino
        {
            get
            {
                return _destino;
            }
            set
            {
                OndestinoChanging(value);
                ReportPropertyChanging("destino");
                _destino = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("destino");
                OndestinoChanged();
            }
        }
        private global::System.String _destino;
        partial void OndestinoChanging(global::System.String value);
        partial void OndestinoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 avion
        {
            get
            {
                return _avion;
            }
            set
            {
                OnavionChanging(value);
                ReportPropertyChanging("avion");
                _avion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("avion");
                OnavionChanged();
            }
        }
        private global::System.Int32 _avion;
        partial void OnavionChanging(global::System.Int32 value);
        partial void OnavionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime salida
        {
            get
            {
                return _salida;
            }
            set
            {
                OnsalidaChanging(value);
                ReportPropertyChanging("salida");
                _salida = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("salida");
                OnsalidaChanged();
            }
        }
        private global::System.DateTime _salida;
        partial void OnsalidaChanging(global::System.DateTime value);
        partial void OnsalidaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime llegada
        {
            get
            {
                return _llegada;
            }
            set
            {
                OnllegadaChanging(value);
                ReportPropertyChanging("llegada");
                _llegada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("llegada");
                OnllegadaChanged();
            }
        }
        private global::System.DateTime _llegada;
        partial void OnllegadaChanging(global::System.DateTime value);
        partial void OnllegadaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.SByte> estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private Nullable<global::System.SByte> _estado;
        partial void OnestadoChanging(Nullable<global::System.SByte> value);
        partial void OnestadoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("airlineModel", "FK_Vuelo_Aerolinea", "aerolinea")]
        public aerolinea aerolinea1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aerolinea>("airlineModel.FK_Vuelo_Aerolinea", "aerolinea").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aerolinea>("airlineModel.FK_Vuelo_Aerolinea", "aerolinea").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<aerolinea> aerolinea1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aerolinea>("airlineModel.FK_Vuelo_Aerolinea", "aerolinea");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<aerolinea>("airlineModel.FK_Vuelo_Aerolinea", "aerolinea", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("airlineModel", "FK_Vuelo_AeropuertoDestino", "aeropuerto")]
        public aeropuerto aeropuerto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aeropuerto>("airlineModel.FK_Vuelo_AeropuertoDestino", "aeropuerto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aeropuerto>("airlineModel.FK_Vuelo_AeropuertoDestino", "aeropuerto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<aeropuerto> aeropuertoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aeropuerto>("airlineModel.FK_Vuelo_AeropuertoDestino", "aeropuerto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<aeropuerto>("airlineModel.FK_Vuelo_AeropuertoDestino", "aeropuerto", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("airlineModel", "FK_Vuelo_AeropuertoOrigen", "aeropuerto")]
        public aeropuerto aeropuerto1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aeropuerto>("airlineModel.FK_Vuelo_AeropuertoOrigen", "aeropuerto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aeropuerto>("airlineModel.FK_Vuelo_AeropuertoOrigen", "aeropuerto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<aeropuerto> aeropuerto1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aeropuerto>("airlineModel.FK_Vuelo_AeropuertoOrigen", "aeropuerto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<aeropuerto>("airlineModel.FK_Vuelo_AeropuertoOrigen", "aeropuerto", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("airlineModel", "FK_Vuelo_Avion", "avion")]
        public avion avion1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<avion>("airlineModel.FK_Vuelo_Avion", "avion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<avion>("airlineModel.FK_Vuelo_Avion", "avion").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<avion> avion1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<avion>("airlineModel.FK_Vuelo_Avion", "avion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<avion>("airlineModel.FK_Vuelo_Avion", "avion", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
